=== MTA-SZTAKI/weblog-demo/repository/dictionaries/dictionaryFileSource.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="urn:hu.sztaki.ilab.longneck:1.0" xmlns:tns="urn:hu.sztaki.ilab.longneck:1.0"
  elementFormDefault="qualified" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
  jaxb:version="2.0">

  <xs:element name="dictionary-elements">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="tns:element" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="element">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="tns:key" />
        <xs:element ref="tns:val" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="key" type="tns:keyType" />
  <xs:element name="val" type="xs:string" />

  <xs:attributeGroup name="keyRegexpAttrGroup">
    <xs:attribute name="regexp" type="xs:boolean" default="false" />
  </xs:attributeGroup>

  <xs:complexType name="keyType" mixed="true">
    <xs:attributeGroup ref="tns:keyRegexpAttrGroup" />
  </xs:complexType>

</xs:schema>

=== MTA-SZTAKI/weblog-demo/repository/dictionaries/url/url_scheme_official.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary-elements xmlns="urn:hu.sztaki.ilab.longneck:1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:hu.sztaki.ilab.longneck:1.0 ../dictionaryFileSource.xsd">

  <!-- Source : http://en.wikipedia.org/wiki/URI_scheme -->

<element>
  <key>aaa<\key>
  <val>aaa<\val>
<\element>

<element>
  <key>aaas<\key>
  <val>aaas<\val>
<\element>

<element>
  <key>about<\key>
  <val>about<\val>
<\element>

<element>
  <key>acap<\key>
  <val>acap<\val>
<\element>

<element>
  <key>cap<\key>
  <val>cap<\val>
<\element>

<element>
  <key>cid<\key>
  <val>cid<\val>
<\element>

<element>
  <key>crid<\key>
  <val>crid<\val>
<\element>

<element>
  <key>data<\key>
  <val>data<\val>
<\element>

<element>
  <key>dav<\key>
  <val>dav<\val>
<\element>

<element>
  <key>dict<\key>
  <val>dict<\val>
<\element>

<element>
  <key>dns<\key>
  <val>dns<\val>
<\element>

<element>
  <key>fax<\key>
  <val>fax<\val>
<\element>

<element>
  <key>file<\key>
  <val>file<\val>
<\element>

<element>
  <key>ftp<\key>
  <val>ftp<\val>
<\element>

<element>
  <key>geo<\key>
  <val>geo<\val>
<\element>

<element>
  <key>go<\key>
  <val>go<\val>
<\element>

<element>
  <key>gopher<\key>
  <val>gopher<\val>
<\element>

<element>
  <key>h323<\key>
  <val>h323<\val>
<\element>

<element>
  <key>http<\key>
  <val>http<\val>
<\element>

<element>
  <key>https<\key>
  <val>https<\val>
<\element>

<element>
  <key>iax<\key>
  <val>iax<\val>
<\element>

<element>
  <key>icap<\key>
  <val>icap<\val>
<\element>

<element>
  <key>im<\key>
  <val>im<\val>
<\element>

<element>
  <key>imap<\key>
  <val>imap<\val>
<\element>

<element>
  <key>info<\key>
  <val>info<\val>
<\element>

<element>
  <key>ipp<\key>
  <val>ipp<\val>
<\element>

<element>
  <key>iris <\key>
  <val>iris <\val>
<\element>

<element>
  <key>iris.beep <\key>
  <val>iris.beep <\val>
<\element>

<element>
  <key>iris.xpc <\key>
  <val>iris.xpc <\val>
<\element>

<element>
  <key>iris.xpcs <\key>
  <val>iris.xpcs <\val>
<\element>

<element>
  <key>iris.lws<\key>
  <val>iris.lws<\val>
<\element>

<element>
  <key>ldap<\key>
  <val>ldap<\val>
<\element>

<element>
  <key>mailto<\key>
  <val>mailto<\val>
<\element>

<element>
  <key>mid<\key>
  <val>mid<\val>
<\element>

<element>
  <key>modem<\key>
  <val>modem<\val>
<\element>

<element>
  <key>msrp <\key>
  <val>msrp <\val>
<\element>

<element>
  <key>msrps<\key>
  <val>msrps<\val>
<\element>

<element>
  <key>mtqp<\key>
  <val>mtqp<\val>
<\element>

<element>
  <key>mupdate<\key>
  <val>mupdate<\val>
<\element>

<element>
  <key>news<\key>
  <val>news<\val>
<\element>

<element>
  <key>nfs<\key>
  <val>nfs<\val>
<\element>

<element>
  <key>nntp<\key>
  <val>nntp<\val>
<\element>

<element>
  <key>opaquelocktoken<\key>
  <val>opaquelocktoken<\val>
<\element>

<element>
  <key>pop<\key>
  <val>pop<\val>
<\element>

<element>
  <key>pres<\key>
  <val>pres<\val>
<\element>

<element>
  <key>prospero<\key>
  <val>prospero<\val>
<\element>

<element>
  <key>rsync<\key>
  <val>rsync<\val>
<\element>

<element>
  <key>rtsp<\key>
  <val>rtsp<\val>
<\element>

<element>
  <key>service<\key>
  <val>service<\val>
<\element>

<element>
  <key>shttp<\key>
  <val>shttp<\val>
<\element>

<element>
  <key>sieve<\key>
  <val>sieve<\val>
<\element>

<element>
  <key>sip<\key>
  <val>sip<\val>
<\element>

<element>
  <key>sips<\key>
  <val>sips<\val>
<\element>

<element>
  <key>sms<\key>
  <val>sms<\val>
<\element>

<element>
  <key>snmp<\key>
  <val>snmp<\val>
<\element>

<element>
  <key>soap.beep <\key>
  <val>soap.beep <\val>
<\element>

<element>
  <key>soap.beeps<\key>
  <val>soap.beeps<\val>
<\element>

<element>
  <key>tag<\key>
  <val>tag<\val>
<\element>

<element>
  <key>tel<\key>
  <val>tel<\val>
<\element>

<element>
  <key>telnet<\key>
  <val>telnet<\val>
<\element>

<element>
  <key>tftp<\key>
  <val>tftp<\val>
<\element>

<element>
  <key>thismessage<\key>
  <val>thismessage<\val>
<\element>

<element>
  <key>tip<\key>
  <val>tip<\val>
<\element>

<element>
  <key>tv<\key>
  <val>tv<\val>
<\element>

<element>
  <key>urn<\key>
  <val>urn<\val>
<\element>

<element>
  <key>uuid<\key>
  <val>uuid<\val>
<\element>

<element>
  <key>vemmi<\key>
  <val>vemmi<\val>
<\element>

<element>
  <key>view-source<\key>
  <val>view-source<\val>
<\element>

<element>
  <key>wais<\key>
  <val>wais<\val>
<\element>

<element>
  <key>ws <\key>
  <val>ws <\val>
<\element>

<element>
  <key>wss<\key>
  <val>wss<\val>
<\element>

<element>
  <key>xmlrpc.beep <\key>
  <val>xmlrpc.beep <\val>
<\element>

<element>
  <key>xmlrpc.beeps<\key>
  <val>xmlrpc.beeps<\val>
<\element>

<element>
  <key>xmpp<\key>
  <val>xmpp<\val>
<\element>

<element>
  <key>z39.50r<\key>
  <val>z39.50r<\val>
<\element>

<element>
  <key>z39.50s<\key>
  <val>z39.50s<\val>
<\element>

<\dictionary-elements>

=== MTA-SZTAKI/weblog-demo/repository/dictionaries/url/url_scheme_unofficial.xml
<?xml version="1.0" encoding="UTF-8"?>
<dictionary-elements xmlns="urn:hu.sztaki.ilab.longneck:1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:hu.sztaki.ilab.longneck:1.0 ../dictionaryFileSource.xsd">

  <!-- Source : http://en.wikipedia.org/wiki/URI_scheme -->

<element>
  <key>adiumxtra<\key>
  <val>adiumxtra<\val>
<\element>

<element>
  <key>aim<\key>
  <val>aim<\val>
<\element>

<element>
  <key>apt<\key>
  <val>apt<\val>
<\element>

<element>
  <key>afp<\key>
  <val>afp<\val>
<\element>

<element>
  <key>attachment<\key>
  <val>attachment<\val>
<\element>

<element>
  <key>aw<\key>
  <val>aw<\val>
<\element>

<element>
  <key>beshare<\key>
  <val>beshare<\val>
<\element>

<element>
  <key>bitcoin<\key>
  <val>bitcoin<\val>
<\element>

<element>
  <key>bolo<\key>
  <val>bolo<\val>
<\element>

<element>
  <key>callto<\key>
  <val>callto<\val>
<\element>

<element>
  <key>chrome<\key>
  <val>chrome<\val>
<\element>

<element>
  <key>chrome-extension<\key>
  <val>chrome-extension<\val>
<\element>

<element>
  <key>coap<\key>
  <val>coap<\val>
<\element>

<element>
  <key>content<\key>
  <val>content<\val>
<\element>

<element>
  <key>cvs<\key>
  <val>cvs<\val>
<\element>

<element>
  <key>doi<\key>
  <val>doi<\val>
<\element>

<element>
  <key>ed2k<\key>
  <val>ed2k<\val>
<\element>

<element>
  <key>facetime<\key>
  <val>facetime<\val>
<\element>

<element>
  <key>feed<\key>
  <val>feed<\val>
<\element>

<element>
  <key>finger<\key>
  <val>finger<\val>
<\element>

<element>
  <key>fish<\key>
  <val>fish<\val>
<\element>

<element>
  <key>git<\key>
  <val>git<\val>
<\element>

<element>
  <key>gg<\key>
  <val>gg<\val>
<\element>

<element>
  <key>gizmoproject<\key>
  <val>gizmoproject<\val>
<\element>

<element>
  <key>gtalk<\key>
  <val>gtalk<\val>
<\element>

<element>
  <key>hcp<\key>
  <val>hcp<\val>
<\element>

<element>
  <key>irc<\key>
  <val>irc<\val>
<\element>

<element>
  <key>ircs<\key>
  <val>ircs<\val>
<\element>

<element>
  <key>irc6<\key>
  <val>irc6<\val>
<\element>

<element>
  <key>itms<\key>
  <val>itms<\val>
<\element>

<element>
  <key>jar<\key>
  <val>jar<\val>
<\element>

<element>
  <key>javascript<\key>
  <val>javascript<\val>
<\element>

<element>
  <key>keyparc<\key>
  <val>keyparc<\val>
<\element>

<element>
  <key>lastfm<\key>
  <val>lastfm<\val>
<\element>

<element>
  <key>ldaps<\key>
  <val>ldaps<\val>
<\element>

<element>
  <key>magnet<\key>
  <val>magnet<\val>
<\element>

<element>
  <key>maps<\key>
  <val>maps<\val>
<\element>

<element>
  <key>market<\key>
  <val>market<\val>
<\element>

<element>
  <key>message<\key>
  <val>message<\val>
<\element>

<element>
  <key>mms<\key>
  <val>mms<\val>
<\element>

<element>
  <key>ms-help<\key>
  <val>ms-help<\val>
<\element>

<element>
  <key>msnim<\key>
  <val>msnim<\val>
<\element>

<element>
  <key>mumble<\key>
  <val>mumble<\val>
<\element>

<element>
  <key>mvn<\key>
  <val>mvn<\val>
<\element>

<element>
  <key>notes<\key>
  <val>notes<\val>
<\element>

<element>
  <key>palm<\key>
  <val>palm<\val>
<\element>

<element>
  <key>paparazzi<\key>
  <val>paparazzi<\val>
<\element>

<element>
  <key>platform<\key>
  <val>platform<\val>
<\element>

<element>
  <key>proxy<\key>
  <val>proxy<\val>
<\element>

<element>
  <key>psyc<\key>
  <val>psyc<\val>
<\element>

<element>
  <key>query<\key>
  <val>query<\val>
<\element>

<element>
  <key>res<\key>
  <val>res<\val>
<\element>

<element>
  <key>resource<\key>
  <val>resource<\val>
<\element>

<element>
  <key>rmi<\key>
  <val>rmi<\val>
<\element>

<element>
  <key>rtmp<\key>
  <val>rtmp<\val>
<\element>

<element>
  <key>secondlife<\key>
  <val>secondlife<\val>
<\element>

<element>
  <key>sgn<\key>
  <val>sgn<\val>
<\element>

<element>
  <key>skype<\key>
  <val>skype<\val>
<\element>

<element>
  <key>spotify<\key>
  <val>spotify<\val>
<\element>

<element>
  <key>ssh<\key>
  <val>ssh<\val>
<\element>

<element>
  <key>sftp<\key>
  <val>sftp<\val>
<\element>

<element>
  <key>smb<\key>
  <val>smb<\val>
<\element>

<element>
  <key>soldat<\key>
  <val>soldat<\val>
<\element>

<element>
  <key>steam<\key>
  <val>steam<\val>
<\element>

<element>
  <key>svn<\key>
  <val>svn<\val>
<\element>

<element>
  <key>teamspeak<\key>
  <val>teamspeak<\val>
<\element>

<element>
  <key>things<\key>
  <val>things<\val>
<\element>

<element>
  <key>udp<\key>
  <val>udp<\val>
<\element>

<element>
  <key>udp<\key>
  <val>udp<\val>
<\element>

<element>
  <key>unreal<\key>
  <val>unreal<\val>
<\element>

<element>
  <key>ut2004<\key>
  <val>ut2004<\val>
<\element>

<element>
  <key>ventrilo<\key>
  <val>ventrilo<\val>
<\element>

<element>
  <key>webcal<\key>
  <val>webcal<\val>
<\element>

<element>
  <key>wtai<\key>
  <val>wtai<\val>
<\element>

<element>
  <key>wyciwyg<\key>
  <val>wyciwyg<\val>
<\element>

<element>
  <key>xfire<\key>
  <val>xfire<\val>
<\element>

<element>
  <key>xri<\key>
  <val>xri<\val>
<\element>

<element>
  <key>ymsgr<\key>
  <val>ymsgr<\val>
<\element>

<\dictionary-elements>
